---

- name: test if hashicorp_installation_method is set correctly
  ansible.builtin.assert:
    that:
      - hashicorp_installation_method is defined
      - hashicorp_installation_method in [ "package", "manual" ]
    quiet: yes

- name: test if hashicorp_products is set correctly
  ansible.builtin.assert:
    that:
      - hashicorp_products is iterable
    quiet: yes
  when:
    - hashicorp_products is defined

- name: test if item in hashicorp_products is set correctly (package)
  ansible.builtin.assert:
    that:
      - item.name is string
      - item.name is regex('^(consul|consul-template|nomad|packer|terraform|vagrant|vault).*')
    quiet: yes
  loop: "{{ hashicorp_products }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - hashicorp_products is defined
    - hashicorp_installation_method == "package"

- name: test if item in hashicorp_products is set correctly (package with version)
  ansible.builtin.assert:
    that:
      - item.name is string
      - item.name is regex('^(consul|consul-template|nomad|packer|terraform|vagrant|vault).*')
    quiet: yes
  loop: "{{ hashicorp_products }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - hashicorp_products is defined
    - hashicorp_installation_method == "package"
    - item.version is defined

- name: test if item in hashicorp_products is set correctly (manual)
  ansible.builtin.assert:
    that:
      - item.name is string
      - item.name is regex('^(consul|nomad|packer|terraform|vagrant|vault).*')
      - item.version is string
    quiet: yes
  loop: "{{ hashicorp_products }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - hashicorp_products is defined
    - hashicorp_installation_method == "manual"
