---
# tasks file for hashicorp

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install using package
  block:
    - name: Install repository for RedHat
      ansible.builtin.get_url:
        url: "{{ hashicorp_repository_url }}"
        dest: /etc/yum.repos.d/hashicorp.repo
      when:
        - ansible_os_family in [ "RedHat", "Rocky" ]

    - name: Configure debian
      block:
        - name: Install apt key for Debian
          ansible.builtin.apt_key:
            url: "https://apt.releases.hashicorp.com/gpg"
            state: present
            validate_certs: no

        - name: Install repository for Debian
          ansible.builtin.apt_repository:
            repo: deb [arch={{ hashicorp_architecture_mapping }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
            state: present
      when:
        - ansible_os_family == "Debian"

    - name: Install hashicorp product using package
      block:
        - name: Install latest hashicorp product using package
          ansible.builtin.package:
            name: "{{ item.name }}"
            state: present
          loop: "{{ hashicorp_products }}"
          loop_control:
            label: "{{ item.name }}"
          when:
            - item.version is not defined

        - name: Install versioned hashicorp product using package
          ansible.builtin.package:
            name: "{{ item.name }}{{ version_coupler }}{{ item.version }}"
            state: present
          loop: "{{ hashicorp_products }}"
          loop_control:
            label: "{{ item.name }}"
          when:
            - item.version is defined
      when:
        - hashicorp_products is defined
  when:
    - hashicorp_installation_method == "package"

- name: Install manually
  block:
    - name: Install hashicorp product manually
      ansible.builtin.unarchive:
        src: "{{ hashicorp_src }}"
        dest: /usr/bin
        mode: "0755"
        remote_src: yes
      loop: "{{ hashicorp_products }}"
      loop_control:
        label: "{{ item.name }}"
  when:
    - hashicorp_installation_method == "manual"
