---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    # - role: robertdebock.hashicorp
    #   hashicorp_products:
    #     - name: consul
    #       version: "1.21.3"
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "1.20.1"
          type: ent
