---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-hashicorp
      hashicorp_products:
        - name: consul
          version: "1.11.3"
    - role: ansible-role-hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "1.9.0"
          type: ent
